import { notFound } from "next/navigation";
import { z } from "zod";
import { CreatorShell } from "@/app/components/creator-shell";
import { ActionForm } from "@/app/components/action-form";
import { withAuthorizedCreator } from "@/src/modules/auth/authorization";
import { domainAction } from "@/src/server/domains/actions";

export default async function DomainManagementPage({params}:{params:Promise<{creatorId:string}>}){
  const {creatorId}=await params;if(!z.string().uuid().safeParse(creatorId).success)notFound();
  const data=await withAuthorizedCreator(creatorId,async(client,_user,role)=>{
    if(!["owner","admin","platform_admin"].includes(role))return null;
    const creator=(await client.query<{name:string;plan:string}>(`SELECT c.name,coalesce(p.name,'Starter') AS plan FROM creators c LEFT JOIN creator_plans cp ON cp.creator_id=c.id AND cp.billing_status<>'cancelled' LEFT JOIN plans p ON p.id=cp.plan_id WHERE c.id=$1 AND c.deleted_at IS NULL LIMIT 1`,[creatorId])).rows[0];
    const domains=(await client.query<{id:string;hostname:string;status:string;ssl_status:string;is_primary:boolean;redirect_to_primary:boolean;last_checked_at:Date|null;last_error:string|null}>("SELECT id,hostname,status::text,ssl_status,is_primary,redirect_to_primary,last_checked_at,last_error FROM creator_domains WHERE creator_id=$1 ORDER BY is_primary DESC,created_at",[creatorId])).rows;
    return creator?{creator,domains}:null;
  });if(!data)notFound();
  const target=process.env.CUSTOM_DOMAIN_CNAME_TARGET||process.env.PLATFORM_HOST||"redlightdist-production.up.railway.app";
  return <CreatorShell creatorId={creatorId} creatorName={data.creator.name} plan={data.creator.plan} section="domain"><div className="creator-console-heading"><div><small>CUSTOM DOMAINS</small><h1>Domain management</h1><p>Verify DNS ownership, choose the primary hostname and track SSL readiness.</p></div></div><section className="creator-card"><h2>DNS instructions</h2><p>Point your domain CNAME/ALIAS to <code>{target}</code>. For each domain, add the TXT record shown below. SSL is tracked independently and must be provisioned by the connected deployment/domain provider.</p></section>{data.domains.map(domain=><section className="creator-card" key={domain.id}><div className="creator-card-head"><div><small>{domain.is_primary?"PRIMARY DOMAIN":"DOMAIN"}</small><h2>{domain.hostname}</h2></div><span className={`creator-status ${domain.status}`}>{domain.status} · SSL {domain.ssl_status}</span></div><p><strong>TXT host:</strong> <code>_redlight.{domain.hostname}</code><br/><strong>TXT value:</strong> <code>redlight-domain-verification={domain.id}</code></p>{domain.last_checked_at&&<p>Last checked {domain.last_checked_at.toLocaleString()}{domain.last_error?` · ${domain.last_error}`:""}</p>}<div className="creator-inline-actions"><ActionForm action={domainAction} label="Verify DNS"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="domainId" value={domain.id}/><input type="hidden" name="operation" value="verify"/></ActionForm>{domain.status==="verified"&&!domain.is_primary&&<ActionForm action={domainAction} label="Make primary"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="domainId" value={domain.id}/><input type="hidden" name="operation" value="primary"/></ActionForm>}{!domain.is_primary&&<ActionForm action={domainAction} label={domain.redirect_to_primary?"Disable redirect":"Redirect to primary"}><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="domainId" value={domain.id}/><input type="hidden" name="operation" value="redirect"/></ActionForm>}</div></section>)}{!data.domains.length&&<section className="creator-card"><p>No custom domains have been added yet. Add one from the Domain section first.</p></section>}</CreatorShell>;
}
