import { notFound } from "next/navigation";
import { z } from "zod";
import { CreatorShell } from "@/app/components/creator-shell";
import { ActionForm } from "@/app/components/action-form";
import { withAuthorizedCreator } from "@/src/modules/auth/authorization";
import { loadCreatorEntitlements } from "@/src/modules/entitlements/server";
import { crmAction } from "@/src/server/crm/actions";

const money=(minor:string|number,currency="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency}).format(Number(minor)/100);
const when=(v:Date|string|null)=>v?new Date(v).toLocaleString():"—";
export default async function FanDetailPage({params}:{params:Promise<{creatorId:string;fanId:string}>}){
  const {creatorId,fanId}=await params;if(!z.string().uuid().safeParse(creatorId).success||!z.string().uuid().safeParse(fanId).success)notFound();
  const data=await withAuthorizedCreator(creatorId,async(client,_actor,role)=>{
    const creator=(await client.query<{name:string}>("SELECT name FROM creators WHERE id=$1 AND deleted_at IS NULL",[creatorId])).rows[0];
    const fan=(await client.query<{id:string;email:string;email_verified_at:Date|null;disabled_at:Date|null;created_at:Date;last_login_at:Date|null;display_name:string|null;phone:string|null;acquisition_source:string|null;utm_source:string|null;utm_medium:string|null;utm_campaign:string|null;referral_source:string|null;email_consent:boolean;sms_consent:boolean}>(`SELECT f.id,f.email,f.email_verified_at,f.disabled_at,f.created_at,f.last_login_at,fp.display_name,fp.phone,fp.acquisition_source,fp.utm_source,fp.utm_medium,fp.utm_campaign,fp.referral_source,coalesce(fp.email_consent,false) email_consent,coalesce(fp.sms_consent,false) sms_consent FROM fans f LEFT JOIN fan_profiles fp ON fp.creator_id=f.creator_id AND fp.fan_id=f.id WHERE f.creator_id=$1 AND f.id=$2`,[creatorId,fanId])).rows[0];if(!creator||!fan)return null;
    const ent=await loadCreatorEntitlements(client,creatorId);
    const subscriptions=(await client.query<{id:string;tier:string;status:string;monthly_price_minor:number;currency:string;current_period_ends_at:Date|null}>("SELECT cs.id,mt.name tier,cs.status,mt.monthly_price_minor,mt.currency,cs.current_period_ends_at FROM creator_subscriptions cs JOIN membership_tiers mt ON mt.creator_id=cs.creator_id AND mt.id=cs.membership_tier_id WHERE cs.creator_id=$1 AND cs.fan_id=$2 ORDER BY cs.created_at DESC",[creatorId,fanId])).rows;
    const transactions=(await client.query<{id:string;kind:string;status:string;gross_minor:number;creator_net_minor:number;currency:string;occurred_at:Date}>("SELECT id,kind,status,gross_minor,creator_net_minor,currency,occurred_at FROM transactions WHERE creator_id=$1 AND fan_id=$2 ORDER BY occurred_at DESC LIMIT 100",[creatorId,fanId])).rows;
    const notes=(await client.query<{id:string;note:string;created_at:Date;author:string|null}>("SELECT n.id,n.note,n.created_at,u.email author FROM fan_notes n LEFT JOIN platform_users u ON u.id=n.author_user_id WHERE n.creator_id=$1 AND n.fan_id=$2 ORDER BY n.created_at DESC LIMIT 100",[creatorId,fanId])).rows;
    const tags=(await client.query<{id:string;name:string;applied:boolean}>("SELECT t.id,t.name,EXISTS(SELECT 1 FROM fan_tags ft WHERE ft.creator_id=t.creator_id AND ft.fan_id=$2 AND ft.tag_id=t.id) applied FROM crm_tags t WHERE t.creator_id=$1 ORDER BY t.name",[creatorId,fanId])).rows;
    const activity=(await client.query<{event_name:string;occurred_at:Date;path:string|null}>("SELECT event_name,occurred_at,path FROM analytics_events WHERE creator_id=$1 AND fan_id=$2 ORDER BY occurred_at DESC LIMIT 50",[creatorId,fanId])).rows;
    const spend=transactions.filter(t=>t.status==="settled").reduce((n,t)=>n+t.gross_minor,0);
    return{creator,fan,role,plan:ent.plan,subscriptions,transactions,notes,tags,activity,spend};
  });if(!data)notFound();
  return <CreatorShell creatorId={creatorId} creatorName={data.creator.name} plan={data.plan.toUpperCase()} section="fans" admin={data.role==="platform_admin"}>
    <div className="office-heading"><a href={`/dashboard/${creatorId}/fans`}>← Fans</a><h1>{data.fan.display_name||data.fan.email}</h1><p>{data.fan.email} · joined {when(data.fan.created_at)} · {data.fan.disabled_at?"suspended":"active"}</p></div>
    <section className="office-stats"><article><span>Lifetime spend</span><strong>{money(data.spend)}</strong></article><article><span>Subscriptions</span><strong>{data.subscriptions.length}</strong></article><article><span>Last login</span><strong className="text-value">{when(data.fan.last_login_at)}</strong></article><article><span>Email verified</span><strong>{data.fan.email_verified_at?"Yes":"No"}</strong></article></section>
    <div className="office-columns"><section className="office-panel"><h2>Profile</h2><ActionForm action={crmAction} label="Save profile"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="fanId" value={fanId}/><input type="hidden" name="operation" value="profile"/><label>Display name<input name="displayName" defaultValue={data.fan.display_name??""}/></label><label>Phone<input name="phone" defaultValue={data.fan.phone??""}/></label><label>Acquisition source<input name="acquisitionSource" defaultValue={data.fan.acquisition_source??""}/></label></ActionForm><p className="office-muted">UTM: {data.fan.utm_source||"—"} / {data.fan.utm_medium||"—"} / {data.fan.utm_campaign||"—"}<br/>Referral: {data.fan.referral_source||"—"}<br/>Consent: email {data.fan.email_consent?"yes":"no"}, SMS {data.fan.sms_consent?"yes":"no"}</p></section>
    <section className="office-panel"><h2>Account controls</h2><ActionForm action={crmAction} label={data.fan.disabled_at?"Restore fan":"Suspend fan"}><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="fanId" value={fanId}/><input type="hidden" name="operation" value={data.fan.disabled_at?"restore":"suspend"}/><p>{data.fan.disabled_at?"Restore login access for this fan.":"Revoke current sessions and prevent login until restored."}</p></ActionForm></section></div>
    <div className="office-columns"><section className="office-panel"><h2>Tags</h2>{data.tags.map(t=><div className="office-row compact" key={t.id}><strong>{t.name}</strong><ActionForm action={crmAction} label={t.applied?"Remove":"Add"}><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="fanId" value={fanId}/><input type="hidden" name="tagId" value={t.id}/><input type="hidden" name="operation" value={t.applied?"remove-tag":"add-tag"}/></ActionForm></div>)}</section><section className="office-panel"><h2>Notes</h2><ActionForm action={crmAction} label="Add note"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="fanId" value={fanId}/><input type="hidden" name="operation" value="add-note"/><label>Private creator note<textarea name="note" rows={4} required/></label></ActionForm>{data.notes.map(n=><div className="office-row compact" key={n.id}><div><strong>{n.author||"Team"}</strong><p>{n.note}</p></div><small>{when(n.created_at)}</small></div>)}</section></div>
    <section className="office-panel"><h2>Memberships</h2>{data.subscriptions.length?data.subscriptions.map(s=><div className="office-row compact" key={s.id}><strong>{s.tier}</strong><span>{money(s.monthly_price_minor,s.currency)}/mo · {s.status} · period ends {when(s.current_period_ends_at)}</span></div>):<p>No memberships.</p>}</section>
    <section className="office-panel"><h2>Transactions</h2>{data.transactions.length?data.transactions.map(t=><div className="office-row compact" key={t.id}><strong>{t.kind} · {t.status}</strong><span>{money(t.gross_minor,t.currency)} gross · {money(t.creator_net_minor,t.currency)} net · {when(t.occurred_at)}</span></div>):<p>No transactions.</p>}</section>
    <section className="office-panel"><h2>Recent activity</h2>{data.activity.length?data.activity.map((a,i)=><div className="office-row compact" key={`${a.event_name}-${i}`}><strong>{a.event_name}</strong><span>{a.path||""} · {when(a.occurred_at)}</span></div>):<p>No tracked activity.</p>}</section>
  </CreatorShell>;
}
