import "server-only";
import { withCreator, withRuntime } from "@/src/server/db/scoped";

export type AnalyticsRange={from:Date;to:Date};
export function analyticsRange(input?:{from?:string|null;to?:string|null;days?:number}){
  const now=new Date();const fallbackDays=Math.max(1,Math.min(input?.days??30,90));
  const to=input?.to?new Date(`${input.to}T23:59:59.999Z`):now;
  const from=input?.from?new Date(`${input.from}T00:00:00.000Z`):new Date(to.getTime()-(fallbackDays-1)*86400000);
  if(Number.isNaN(from.getTime())||Number.isNaN(to.getTime())||from>to||to.getTime()-from.getTime()>91*86400000)throw new Error("INVALID_ANALYTICS_RANGE");return{from,to};
}

export async function refreshAnalyticsRollups(days=35){const bounded=Math.max(1,Math.min(days,90));const today=new Date();const to=today.toISOString().slice(0,10);const from=new Date(today.getTime()-(bounded-1)*86400000).toISOString().slice(0,10);return withRuntime(async client=>Number((await client.query<{count:number}>("SELECT refresh_daily_creator_metrics($1::date,$2::date) count",[from,to])).rows[0]?.count??0));}

export async function creatorAnalytics(creatorId:string,range:AnalyticsRange){return withCreator(creatorId,async client=>{
  const rows=(await client.query<{metric_date:string;page_views:string;unique_visitors:string;registrations:string;new_subscribers:string;cancellations:string;ppv_sales:string;tips_minor:string;gross_revenue_minor:string;net_revenue_minor:string}>(`SELECT metric_date::text,page_views::text,unique_visitors::text,registrations::text,new_subscribers::text,cancellations::text,ppv_sales::text,tips_minor::text,gross_revenue_minor::text,net_revenue_minor::text FROM daily_creator_metrics WHERE creator_id=$1 AND metric_date BETWEEN $2::date AND $3::date ORDER BY metric_date`,[creatorId,range.from.toISOString().slice(0,10),range.to.toISOString().slice(0,10)])).rows;
  const acquisition=(await client.query<{source:string;fans:string;revenue:string}>(`SELECT coalesce(nullif(fp.utm_source,''),nullif(fp.acquisition_source,''),nullif(fp.referral_source,''),'direct') source,count(DISTINCT f.id)::text fans,coalesce(sum(t.gross_minor) FILTER(WHERE t.status='settled'),0)::text revenue FROM fans f LEFT JOIN fan_profiles fp ON fp.creator_id=f.creator_id AND fp.fan_id=f.id LEFT JOIN transactions t ON t.creator_id=f.creator_id AND t.fan_id=f.id WHERE f.creator_id=$1 AND f.created_at BETWEEN $2 AND $3 GROUP BY 1 ORDER BY sum(t.gross_minor) DESC NULLS LAST,count(DISTINCT f.id) DESC LIMIT 20`,[creatorId,range.from,range.to])).rows;
  const cohorts=(await client.query<{cohort:string;signups:string;subscribers:string;revenue:string}>(`SELECT to_char(date_trunc('week',f.created_at),'YYYY-MM-DD') cohort,count(*)::text signups,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM creator_subscriptions s WHERE s.creator_id=f.creator_id AND s.fan_id=f.id))::text subscribers,coalesce(sum((SELECT sum(t.gross_minor) FROM transactions t WHERE t.creator_id=f.creator_id AND t.fan_id=f.id AND t.status='settled')),0)::text revenue FROM fans f WHERE f.creator_id=$1 AND f.created_at BETWEEN $2 AND $3 GROUP BY date_trunc('week',f.created_at) ORDER BY date_trunc('week',f.created_at)`,[creatorId,range.from,range.to])).rows;
  const content=(await client.query<{id:string;title:string;views:string;purchases:string;revenue:string}>(`SELECT p.id,coalesce(p.title,'Untitled') title,count(DISTINCT a.id) FILTER(WHERE a.event_name='content_view')::text views,count(DISTINCT pu.id) FILTER(WHERE pu.status='paid')::text purchases,coalesce(sum(t.gross_minor) FILTER(WHERE t.status='settled'),0)::text revenue FROM content_posts p LEFT JOIN analytics_events a ON a.creator_id=p.creator_id AND a.content_id=p.id AND a.occurred_at BETWEEN $2 AND $3 LEFT JOIN content_access_rules r ON r.creator_id=p.creator_id AND r.post_id=p.id AND r.product_id IS NOT NULL LEFT JOIN purchases pu ON pu.creator_id=p.creator_id AND pu.product_id=r.product_id AND pu.purchased_at BETWEEN $2 AND $3 LEFT JOIN transactions t ON t.creator_id=pu.creator_id AND t.purchase_id=pu.id WHERE p.creator_id=$1 GROUP BY p.id,p.title ORDER BY count(DISTINCT a.id) DESC LIMIT 20`,[creatorId,range.from,range.to])).rows;
  const totals=rows.reduce((a,r)=>({views:a.views+Number(r.page_views),visitors:a.visitors+Number(r.unique_visitors),registrations:a.registrations+Number(r.registrations),subs:a.subs+Number(r.new_subscribers),cancels:a.cancels+Number(r.cancellations),gross:a.gross+Number(r.gross_revenue_minor),net:a.net+Number(r.net_revenue_minor)}),{views:0,visitors:0,registrations:0,subs:0,cancels:0,gross:0,net:0});
  return{rows,acquisition,cohorts,content,totals};
});}
