import { notFound } from "next/navigation";
import { CreatorShell } from "@/app/components/creator-shell";
import { ActionForm } from "@/app/components/action-form";
import { creatorAction } from "./actions";
import { withAuthorizedCreator } from "@/src/modules/auth/authorization";
import { loadCreatorEntitlements } from "@/src/modules/entitlements/server";
import { planIncludesFeature, type Feature, type Plan } from "@/src/modules/entitlements/policy";

export const creatorSections=["overview","content","subscribers","fans","memberships","ppv","products","revenue","analytics","marketing","discounts","referrals","messages","livestreams","settings","domain","branding","payments","compliance","billing"] as const;
export type CreatorSection=(typeof creatorSections)[number];

const money=(minor:number|string|null|undefined,currency="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency}).format(Number(minor??0)/100);
const num=(value:number|string|null|undefined)=>new Intl.NumberFormat("en-US").format(Number(value??0));
const date=(value:Date|string|null|undefined)=>value?new Date(value).toLocaleString():"—";

function Heading({title,description}:{title:string;description:string}){return <div className="office-heading creator-page-heading"><h1>{title}</h1><p>{description}</p></div>}
function Empty({children}:{children:string}){return <p className="office-empty">{children}</p>}
function Gate({plan,feature,children}:{plan:Plan;feature:Feature;children:React.ReactNode}){return planIncludesFeature(plan,feature)?<>{children}</>:<section className="office-panel feature-lock"><h2>Upgrade required</h2><p>This capability is not included with the {plan} plan.</p><a className="office-button" href="#plan-billing">View plan options</a></section>}

async function Overview({creatorId}:{creatorId:string}){
  const data=await withAuthorizedCreator(creatorId,async client=>{
    const metrics=(await client.query<{today:string;month:string;mrr:string;active:string;new_subscribers:string;cancellations:string;ppv:string;tips:string;page_views:string;visitors:string;registrations:string}>(`SELECT
      (SELECT coalesce(sum(creator_net_minor),0)::text FROM transactions WHERE creator_id=$1 AND status='settled' AND occurred_at>=date_trunc('day',now())) today,
      (SELECT coalesce(sum(creator_net_minor),0)::text FROM transactions WHERE creator_id=$1 AND status='settled' AND occurred_at>=date_trunc('month',now())) month,
      (SELECT coalesce(sum(mt.monthly_price_minor),0)::text FROM creator_subscriptions cs JOIN membership_tiers mt ON mt.creator_id=cs.creator_id AND mt.id=cs.membership_tier_id WHERE cs.creator_id=$1 AND cs.status='active') mrr,
      (SELECT count(*)::text FROM creator_subscriptions WHERE creator_id=$1 AND status='active') active,
      (SELECT count(*)::text FROM creator_subscriptions WHERE creator_id=$1 AND created_at>=date_trunc('month',now())) new_subscribers,
      (SELECT count(*)::text FROM creator_subscriptions WHERE creator_id=$1 AND cancelled_at>=date_trunc('month',now())) cancellations,
      (SELECT count(*)::text FROM purchases p JOIN products pr ON pr.creator_id=p.creator_id AND pr.id=p.product_id WHERE p.creator_id=$1 AND p.status='paid' AND pr.product_type='ppv' AND p.created_at>=date_trunc('month',now())) ppv,
      (SELECT coalesce(sum(amount_minor),0)::text FROM tips WHERE creator_id=$1 AND created_at>=date_trunc('month',now())) tips,
      (SELECT count(*)::text FROM analytics_events WHERE creator_id=$1 AND event_name='page_view' AND occurred_at>=date_trunc('month',now())) page_views,
      (SELECT count(DISTINCT coalesce(fan_id::text,anonymous_id,session_id))::text FROM analytics_events WHERE creator_id=$1 AND event_name='page_view' AND occurred_at>=date_trunc('month',now())) visitors,
      (SELECT count(*)::text FROM fans WHERE creator_id=$1 AND created_at>=date_trunc('month',now())) registrations`,[creatorId])).rows[0]!;
    const recent=(await client.query<{id:string;kind:string;status:string;gross_minor:number;creator_net_minor:number;currency:string;occurred_at:Date}>("SELECT id,kind,status,gross_minor,creator_net_minor,currency,occurred_at FROM transactions WHERE creator_id=$1 ORDER BY occurred_at DESC LIMIT 8",[creatorId])).rows;
    const topContent=(await client.query<{title:string|null;views:string}>("SELECT coalesce(p.title,'Untitled post') title,count(a.id)::text views FROM content_posts p LEFT JOIN analytics_events a ON a.creator_id=p.creator_id AND a.content_id=p.id AND a.event_name='content_view' WHERE p.creator_id=$1 GROUP BY p.id,p.title ORDER BY count(a.id) DESC,p.created_at DESC LIMIT 5",[creatorId])).rows;
    const topFans=(await client.query<{email:string;spend:string}>("SELECT f.email,coalesce(sum(t.gross_minor),0)::text spend FROM fans f LEFT JOIN transactions t ON t.creator_id=f.creator_id AND t.fan_id=f.id AND t.status='settled' WHERE f.creator_id=$1 GROUP BY f.id,f.email ORDER BY sum(t.gross_minor) DESC NULLS LAST,f.created_at DESC LIMIT 5",[creatorId])).rows;
    return {metrics,recent,topContent,topFans};
  });
  const visitors=Number(data.metrics.visitors); const registrations=Number(data.metrics.registrations); const conversion=visitors?registrations/visitors*100:0;
  return <><Heading title="Overview" description="Revenue, subscribers, content performance and conversion from live tenant data."/>
    <section className="office-stats dashboard-kpis">{[
      ["Revenue today",money(data.metrics.today)],["Revenue this month",money(data.metrics.month)],["MRR",money(data.metrics.mrr)],["Active subscribers",num(data.metrics.active)],
      ["New subscribers",num(data.metrics.new_subscribers)],["Cancellations",num(data.metrics.cancellations)],["PPV sales",num(data.metrics.ppv)],["Tips",money(data.metrics.tips)],
      ["Traffic",num(data.metrics.page_views)],["Conversion rate",`${conversion.toFixed(1)}%`],
    ].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <div className="office-columns"><section className="office-panel"><h2>Top content</h2>{data.topContent.length?data.topContent.map(row=><div className="office-row compact" key={`${row.title}-${row.views}`}><strong>{row.title}</strong><span>{num(row.views)} views</span></div>):<Empty>No published content performance yet.</Empty>}</section><section className="office-panel"><h2>Top fans</h2>{data.topFans.length?data.topFans.map(row=><div className="office-row compact" key={row.email}><strong>{row.email}</strong><span>{money(row.spend)}</span></div>):<Empty>No fan spending data yet.</Empty>}</section></div>
    <section className="office-panel"><h2>Recent transactions</h2>{data.recent.length?data.recent.map(tx=><div className="office-row compact" key={tx.id}><div><strong>{tx.kind}</strong><small>{date(tx.occurred_at)}</small></div><span>{money(tx.creator_net_minor,tx.currency)} net · {tx.status}</span></div>):<Empty>No transactions yet.</Empty>}</section>
  </>;
}

async function Content({creatorId,plan}:{creatorId:string;plan:Plan}){
  const data=await withAuthorizedCreator(creatorId,async client=>({
    posts:(await client.query<{id:string;title:string|null;post_type:string;status:string;access_type:string;published_at:Date|null}>("SELECT id,title,post_type,status,access_type,published_at FROM content_posts WHERE creator_id=$1 ORDER BY created_at DESC LIMIT 100",[creatorId])).rows,
    tiers:(await client.query<{id:string;name:string}>("SELECT id,name FROM membership_tiers WHERE creator_id=$1 AND active ORDER BY position,name",[creatorId])).rows,
  }));
  return <><Heading title="Content" description="Draft, schedule and publish public, subscriber, membership and PPV content."/><section className="office-panel"><h2>Create post</h2><ActionForm action={creatorAction} label="Create post"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="post"/><label>Title<input name="title" maxLength={200}/></label><label>Body<textarea name="body" rows={5}/></label><label>Type<select name="postType" defaultValue="text"><option value="text">Text</option><option value="image">Image</option><option value="video">Video</option><option value="gallery">Gallery</option><option value="mixed">Mixed media</option></select></label><label>Access<select name="accessType" defaultValue="public"><option value="public">Public</option><option value="subscriber">Subscribers</option><option value="membership">Membership tier</option>{planIncludesFeature(plan,"ppv")&&<option value="ppv">PPV</option>}</select></label><label>Membership tier<select name="membershipTierId" defaultValue=""><option value="">Not tier-specific</option>{data.tiers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>PPV price<input name="price" type="number" min="0" step="0.01"/></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="published">Publish now</option></select></label></ActionForm></section><section className="office-list">{data.posts.length?data.posts.map(post=><article className="office-panel office-row" key={post.id}><div><h2>{post.title||"Untitled post"}</h2><p>{post.post_type} · {post.access_type} · {post.status}</p></div><span>{date(post.published_at)}</span></article>):<Empty>No content yet.</Empty>}</section></>;
}

async function Subscribers({creatorId}:{creatorId:string}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{id:string;email:string;tier:string;status:string;created_at:Date;current_period_ends_at:Date|null}>("SELECT cs.id,f.email,mt.name tier,cs.status,cs.created_at,cs.current_period_ends_at FROM creator_subscriptions cs JOIN fans f ON f.creator_id=cs.creator_id AND f.id=cs.fan_id JOIN membership_tiers mt ON mt.creator_id=cs.creator_id AND mt.id=cs.membership_tier_id WHERE cs.creator_id=$1 ORDER BY cs.created_at DESC LIMIT 200",[creatorId])).rows);
  return <><Heading title="Subscribers" description="Membership status, tier and renewal timing."/><section className="office-list">{rows.length?rows.map(row=><article className="office-panel office-row" key={row.id}><div><strong>{row.email}</strong><p>{row.tier} · {row.status}</p></div><span>Renews / ends {date(row.current_period_ends_at)}</span></article>):<Empty>No subscriptions yet.</Empty>}</section></>;
}

async function Fans({creatorId,plan}:{creatorId:string;plan:Plan}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{id:string;email:string;display_name:string|null;created_at:Date;lifetime:string;last_login_at:Date|null}>("SELECT f.id,f.email,fp.display_name,f.created_at,f.last_login_at,coalesce((SELECT sum(t.gross_minor) FROM transactions t WHERE t.creator_id=f.creator_id AND t.fan_id=f.id AND t.status='settled'),0)::text lifetime FROM fans f LEFT JOIN fan_profiles fp ON fp.creator_id=f.creator_id AND fp.fan_id=f.id WHERE f.creator_id=$1 ORDER BY f.created_at DESC LIMIT 200",[creatorId])).rows);
  return <><Heading title="Customers / Fans" description="Registration, spending and engagement data for this creator only."/><Gate plan={plan} feature="crm"><section className="office-panel"><h2>CRM tags</h2><ActionForm action={creatorAction} label="Create tag"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="tag"/><label>Tag name<input name="name" required/></label></ActionForm></section></Gate><section className="office-list">{rows.length?rows.map(row=><article className="office-panel office-row" key={row.id}><div><strong>{row.display_name||row.email}</strong><p>{row.email} · joined {date(row.created_at)}</p></div><div><strong>{money(row.lifetime)}</strong><small>Last login {date(row.last_login_at)}</small></div></article>):<Empty>No fan accounts yet.</Empty>}</section></>;
}

async function Memberships({creatorId,plan}:{creatorId:string;plan:Plan}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{id:string;name:string;slug:string;monthly_price_minor:number;currency:string;active:boolean;description:string}>("SELECT id,name,slug,monthly_price_minor,currency,active,description FROM membership_tiers WHERE creator_id=$1 ORDER BY position,name",[creatorId])).rows);
  return <><Heading title="Memberships" description="Creator-controlled monthly membership tiers."/><section className="office-panel"><h2>Add membership tier</h2><ActionForm action={creatorAction} label="Create membership"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="membership"/><label>Name<input name="name" required/></label><label>URL slug<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*"/></label><label>Monthly price<input name="price" type="number" step="0.01" min="0" required/></label><label>Description<textarea name="description" rows={4}/></label></ActionForm><p className="office-muted">{plan==="starter"?"Starter supports one membership tier.":"Your plan supports multiple membership tiers."}</p></section><section className="office-list">{rows.length?rows.map(row=><article className="office-panel office-row" key={row.id}><div><h2>{row.name}</h2><p>{row.description||row.slug}</p></div><strong>{money(row.monthly_price_minor,row.currency)}/mo</strong></article>):<Empty>No membership tiers yet.</Empty>}</section></>;
}

async function Products({creatorId,plan,ppvOnly=false}:{creatorId:string;plan:Plan;ppvOnly?:boolean}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{id:string;name:string;product_type:string;price_minor:number;currency:string;active:boolean}>(`SELECT id,name,product_type,price_minor,currency,active FROM products WHERE creator_id=$1 ${ppvOnly?"AND product_type='ppv'":""} ORDER BY created_at DESC LIMIT 100`,[creatorId])).rows);
  return <><Heading title={ppvOnly?"PPV":"Products"} description={ppvOnly?"Pay-per-view offers and locked content products.":"Digital products, bundles, PPV and replay offers."}/><Gate plan={plan} feature="ppv"><section className="office-panel"><h2>Create paid product</h2><ActionForm action={creatorAction} label="Create product"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="product"/><label>Name<input name="name" required/></label><label>Description<textarea name="description" rows={4}/></label><label>Type<select name="productType" defaultValue={ppvOnly?"ppv":"digital"}><option value="ppv">PPV</option><option value="bundle">Bundle</option><option value="digital">Digital</option><option value="replay">Replay</option></select></label><label>Price<input name="price" type="number" step="0.01" min="0.50" required/></label></ActionForm></section></Gate><section className="office-list">{rows.length?rows.map(row=><article className="office-panel office-row" key={row.id}><div><strong>{row.name}</strong><p>{row.product_type} · {row.active?"active":"inactive"}</p></div><strong>{money(row.price_minor,row.currency)}</strong></article>):<Empty>No paid products yet.</Empty>}</section></>;
}

async function Revenue({creatorId}:{creatorId:string}){
  const data=await withAuthorizedCreator(creatorId,async client=>({
    totals:(await client.query<{gross:string;fees:string;refunds:string;chargebacks:string;platform:string;net:string}>("SELECT coalesce(sum(gross_minor),0)::text gross,coalesce(sum(processor_fee_minor),0)::text fees,coalesce(sum(refund_minor),0)::text refunds,coalesce(sum(chargeback_minor),0)::text chargebacks,coalesce(sum(platform_fee_minor),0)::text platform,coalesce(sum(creator_net_minor),0)::text net FROM transactions WHERE creator_id=$1 AND status IN ('settled','refunded','chargeback')",[creatorId])).rows[0]!,
    tx:(await client.query<{id:string;kind:string;status:string;gross_minor:number;processor_fee_minor:number;creator_net_minor:number;currency:string;occurred_at:Date}>("SELECT id,kind,status,gross_minor,processor_fee_minor,creator_net_minor,currency,occurred_at FROM transactions WHERE creator_id=$1 ORDER BY occurred_at DESC LIMIT 100",[creatorId])).rows,
  }));
  return <><Heading title="Revenue" description="Gross sales, fees, refunds, chargebacks and creator net revenue."/><section className="office-stats">{[["Gross",data.totals.gross],["Processor fees",data.totals.fees],["Refunds",data.totals.refunds],["Chargebacks",data.totals.chargebacks],["Platform fees",data.totals.platform],["Creator net",data.totals.net]].map(([l,v])=><article key={l}><span>{l}</span><strong>{money(v)}</strong></article>)}</section><section className="office-list">{data.tx.length?data.tx.map(row=><article className="office-panel office-row" key={row.id}><div><strong>{row.kind} · {row.status}</strong><p>{date(row.occurred_at)}</p></div><span>{money(row.gross_minor,row.currency)} gross · {money(row.creator_net_minor,row.currency)} net</span></article>):<Empty>No transaction history yet.</Empty>}</section></>;
}

async function Analytics({creatorId,plan}:{creatorId:string;plan:Plan}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{metric_date:string;page_views:string;unique_visitors:string;registrations:string;new_subscribers:string;cancellations:string;gross_revenue_minor:string;net_revenue_minor:string}>("SELECT metric_date::text,page_views::text,unique_visitors::text,registrations::text,new_subscribers::text,cancellations::text,gross_revenue_minor::text,net_revenue_minor::text FROM daily_creator_metrics WHERE creator_id=$1 ORDER BY metric_date DESC LIMIT 90",[creatorId])).rows);
  return <><Heading title="Analytics" description="First-party traffic, conversion, subscriber and revenue metrics."/><Gate plan={plan} feature="basicAnalytics"><section className="office-panel"><h2>Daily metrics</h2>{rows.length?rows.map(row=><div className="office-row compact" key={row.metric_date}><strong>{row.metric_date}</strong><span>{num(row.page_views)} views · {num(row.unique_visitors)} visitors · {num(row.new_subscribers)} new subs · {money(row.net_revenue_minor)} net</span></div>):<Empty>No aggregated analytics yet. Events will populate this view as traffic arrives.</Empty>}</section></Gate>{planIncludesFeature(plan,"advancedAnalytics")?<section className="office-panel"><h2>Advanced analytics</h2><p>Revenue attribution, LTV, churn, traffic sources, UTMs, content performance and subscriber value use the same first-party event and transaction records.</p></section>:<section className="office-panel feature-lock"><h2>Advanced analytics</h2><p>Upgrade to Pro or Elite for attribution, LTV, churn and advanced conversion reporting.</p></section>}</>;
}

async function Marketing({creatorId,plan}:{creatorId:string;plan:Plan}){
  const data=await withAuthorizedCreator(creatorId,async client=>({campaigns:(await client.query<{id:string;name:string;channel:string;status:string;scheduled_for:Date|null}>("SELECT id,name,channel,status,scheduled_for FROM campaigns WHERE creator_id=$1 ORDER BY created_at DESC LIMIT 100",[creatorId])).rows,automations:(await client.query<{id:string;name:string;status:string}>("SELECT id,name,status FROM automations WHERE creator_id=$1 ORDER BY created_at DESC LIMIT 100",[creatorId])).rows}));
  return <><Heading title="Marketing" description="Campaigns and event-driven automation without hard-coded workflows."/><Gate plan={plan} feature="emailAutomation"><section className="office-panel"><h2>Create campaign</h2><ActionForm action={creatorAction} label="Save campaign"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="campaign"/><label>Name<input name="name" required/></label><label>Channel<select name="channel" defaultValue="email"><option value="email">Email</option><option value="in_app">In-app</option>{planIncludesFeature(plan,"sms")&&<option value="sms">SMS</option>}</select></label><label>Subject<input name="subject"/></label><label>Message<textarea name="body" rows={6} required/></label></ActionForm>{data.campaigns.map(c=><div className="office-row compact" key={c.id}><strong>{c.name}</strong><span>{c.channel} · {c.status}</span></div>)}</section></Gate><Gate plan={plan} feature="automation"><section className="office-panel"><h2>Automation builder</h2><ActionForm action={creatorAction} label="Create automation"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="automation"/><label>Name<input name="name" required/></label><label>WHEN event<input name="eventKey" placeholder="fan.subscribed" required/></label><label>THEN action<input name="actionKey" placeholder="email.send" required/></label></ActionForm>{data.automations.map(a=><div className="office-row compact" key={a.id}><strong>{a.name}</strong><span>{a.status}</span></div>)}</section></Gate></>;
}

async function Discounts({creatorId,plan}:{creatorId:string;plan:Plan}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{id:string;code:string;discount_type:string;discount_value:number;active:boolean}>("SELECT id,code,discount_type,discount_value,active FROM coupons WHERE creator_id=$1 ORDER BY created_at DESC",[creatorId])).rows);
  return <><Heading title="Discounts" description="Coupons, promotions and trial offers."/><Gate plan={plan} feature="discounts"><section className="office-panel"><ActionForm action={creatorAction} label="Create coupon"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="coupon"/><label>Code<input name="code" required/></label><label>Discount type<select name="discountType"><option value="percent">Percent</option><option value="fixed">Fixed amount (minor units)</option><option value="trial_days">Trial days</option></select></label><label>Value<input name="discountValue" type="number" min="1" step="1" required/></label></ActionForm>{rows.map(row=><div className="office-row compact" key={row.id}><strong>{row.code}</strong><span>{row.discount_type} · {row.discount_value} · {row.active?"active":"inactive"}</span></div>)}</section></Gate></>;
}

async function Referrals({creatorId,plan}:{creatorId:string;plan:Plan}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{id:string;code:string;status:string;reward_minor:number;created_at:Date}>("SELECT id,code,status,reward_minor,created_at FROM referrals WHERE creator_id=$1 ORDER BY created_at DESC LIMIT 100",[creatorId])).rows);
  return <><Heading title="Referrals" description="Fan referrals and affiliate attribution."/><Gate plan={plan} feature="referrals"><section className="office-panel"><h2>Referral activity</h2>{rows.length?rows.map(row=><div className="office-row compact" key={row.id}><strong>{row.code}</strong><span>{row.status} · {money(row.reward_minor)}</span></div>):<Empty>No referrals yet.</Empty>}</section></Gate></>;
}

async function Messages({creatorId}:{creatorId:string}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{id:string;channel:string;subject:string|null;status:string;scheduled_for:Date|null;sent_at:Date|null}>("SELECT id,channel,subject,status,scheduled_for,sent_at FROM notifications WHERE creator_id=$1 ORDER BY created_at DESC LIMIT 100",[creatorId])).rows);
  return <><Heading title="Messages / Notifications" description="Queued, scheduled and delivered fan communications."/><section className="office-panel">{rows.length?rows.map(row=><div className="office-row compact" key={row.id}><strong>{row.subject||row.channel}</strong><span>{row.channel} · {row.status} · {date(row.sent_at??row.scheduled_for)}</span></div>):<Empty>No notifications yet.</Empty>}</section></>;
}

async function Livestreams({creatorId,plan}:{creatorId:string;plan:Plan}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{id:string;title:string;status:string;access_type:string;scheduled_for:Date|null;started_at:Date|null;ended_at:Date|null;ppv_price_minor:number|null;currency:string}>("SELECT id,title,status,access_type,scheduled_for,started_at,ended_at,ppv_price_minor,currency FROM live_streams WHERE creator_id=$1 ORDER BY created_at DESC LIMIT 100",[creatorId])).rows);
  return <><Heading title="Livestreams" description="Schedule subscriber streams, chat, tips, replays and Elite paid live events."/><Gate plan={plan} feature="live"><section className="office-panel"><h2>Schedule stream</h2><ActionForm action={creatorAction} label="Schedule stream"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="stream"/><label>Title<input name="title" required/></label><label>Description<textarea name="description" rows={4}/></label><label>Access<select name="accessType" defaultValue="subscriber"><option value="public">Public</option><option value="subscriber">Subscribers</option>{planIncludesFeature(plan,"livePrivateTiers")&&<option value="membership">VIP / membership tier</option>}{planIncludesFeature(plan,"livePpv")&&<option value="ppv">PPV live event</option>}</select></label><label>PPV price<input name="price" type="number" min="0" step="0.01"/></label><label>Scheduled time<input name="scheduledFor" type="datetime-local"/></label><label className="check-label"><input name="chatEnabled" type="checkbox" defaultChecked/> Enable live chat</label></ActionForm></section></Gate><section className="office-list">{rows.length?rows.map(row=><article className="office-panel office-row" key={row.id}><div><strong>{row.title}</strong><p>{row.access_type} · {row.status}</p></div><span>{row.ppv_price_minor!==null?`${money(row.ppv_price_minor,row.currency)} · `:""}{date(row.scheduled_for??row.started_at??row.ended_at)}</span></article>):<Empty>No streams scheduled.</Empty>}</section></>;
}

async function Branding({creatorId}:{creatorId:string}){
  const data=await withAuthorizedCreator(creatorId,async client=>(await client.query<{name:string;bio:string;preset:string|null;settings:Record<string,string>}>("SELECT c.name,coalesce(s.bio,'') bio,t.preset,s.settings FROM creators c LEFT JOIN creator_settings s ON s.creator_id=c.id LEFT JOIN creator_themes t ON t.creator_id=c.id AND t.id=s.theme_id WHERE c.id=$1",[creatorId])).rows[0]!);
  const settings=data.settings??{};
  return <><Heading title="Branding" description="One application, tenant-specific brand tokens and reusable themes."/><section className="office-panel"><ActionForm action={creatorAction} label="Save branding"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="branding"/><label>Creator name<input name="name" defaultValue={data.name} required/></label><label>Bio<textarea name="bio" rows={6} defaultValue={data.bio}/></label><label>Theme<select name="preset" defaultValue={data.preset??"dark"}><option value="luxury">Luxury</option><option value="dark">Dark</option><option value="minimal">Minimal</option><option value="glam">Pink / Glam</option><option value="lifestyle">Lifestyle</option></select></label><label>Primary color<input name="primaryColor" type="color" defaultValue={settings.primaryColor??"#7c5cff"}/></label><label>Secondary color<input name="secondaryColor" type="color" defaultValue={settings.secondaryColor??"#20273a"}/></label><label>Accent color<input name="accentColor" type="color" defaultValue={settings.accentColor??"#24d3ee"}/></label></ActionForm></section></>;
}

async function Domains({creatorId}:{creatorId:string}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{id:string;hostname:string;status:string;is_primary:boolean;verified_at:Date|null}>("SELECT id,hostname,status,is_primary,verified_at FROM creator_domains WHERE creator_id=$1 ORDER BY is_primary DESC,created_at DESC",[creatorId])).rows);
  return <><Heading title="Domain" description="Platform subdomain plus verified custom domains. Unknown hosts fail closed."/><section className="office-panel"><h2>Connect domain</h2><ActionForm action={creatorAction} label="Add domain"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="domain"/><label>Hostname<input name="hostname" placeholder="creatorname.com" required/></label><p>DNS verification and SSL activation remain pending until the deployment provider is configured for automated domain provisioning.</p></ActionForm></section><section className="office-list">{rows.length?rows.map(row=><article className="office-panel office-row" key={row.id}><strong>{row.hostname}</strong><span>{row.status}{row.is_primary?" · primary":""} · {date(row.verified_at)}</span></article>):<Empty>No custom domains connected.</Empty>}</section></>;
}

async function Payments({creatorId}:{creatorId:string}){
  const rows=await withAuthorizedCreator(creatorId,async client=>(await client.query<{id:string;provider:string;merchant_reference:string|null;status:string;is_default:boolean}>("SELECT id,provider,merchant_reference,status,is_default FROM payment_provider_accounts WHERE creator_id=$1 ORDER BY is_default DESC,created_at DESC",[creatorId])).rows);
  return <><Heading title="Payment settings" description="Creator-to-fan processing is provider-agnostic and separate from platform SaaS billing."/><section className="office-panel"><h2>Connect merchant processor</h2><ActionForm action={creatorAction} label="Add processor"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="payment-provider"/><label>Provider<select name="provider"><option value="ccbill">CCBill</option><option value="segpay">Segpay</option><option value="stripe">Stripe (non-adult verticals only where eligible)</option></select></label><label>Merchant / account reference<input name="merchantReference" required/></label><p>Credentials are never entered into creator-visible database fields. Production activation requires server-side secrets and approved merchant configuration.</p></ActionForm></section><section className="office-list">{rows.length?rows.map(row=><article className="office-panel office-row" key={row.id}><strong>{row.provider}</strong><span>{row.merchant_reference} · {row.status}{row.is_default?" · default":""}</span></article>):<Empty>No payment processor configured.</Empty>}</section></>;
}

async function Compliance({creatorId}:{creatorId:string}){
  const data=await withAuthorizedCreator(creatorId,async client=>({records:(await client.query<{id:string;requirement_key:string;subject_type:string;status:string;expires_at:Date|null}>("SELECT id,requirement_key,subject_type,status,expires_at FROM compliance_records WHERE creator_id=$1 ORDER BY updated_at DESC LIMIT 100",[creatorId])).rows,reports:(await client.query<{id:string;reason_key:string;status:string;created_at:Date}>("SELECT id,reason_key,status,created_at FROM reports WHERE creator_id=$1 ORDER BY created_at DESC LIMIT 50",[creatorId])).rows,takedowns:(await client.query<{id:string;content_reference:string;status:string;created_at:Date}>("SELECT id,content_reference,status,created_at FROM takedown_requests WHERE creator_id=$1 ORDER BY created_at DESC LIMIT 50",[creatorId])).rows}));
  return <><Heading title="Compliance" description="Configurable verification, consent, reporting and takedown records. Jurisdiction rules require legal review."/><section className="office-panel"><h2>Verification / compliance records</h2>{data.records.length?data.records.map(r=><div className="office-row compact" key={r.id}><strong>{r.requirement_key}</strong><span>{r.subject_type} · {r.status} · expires {date(r.expires_at)}</span></div>):<Empty>No compliance records yet.</Empty>}</section><div className="office-columns"><section className="office-panel"><h2>Abuse reports</h2>{data.reports.length?data.reports.map(r=><div className="office-row compact" key={r.id}><strong>{r.reason_key}</strong><span>{r.status} · {date(r.created_at)}</span></div>):<Empty>No reports.</Empty>}</section><section className="office-panel"><h2>Takedowns</h2>{data.takedowns.length?data.takedowns.map(r=><div className="office-row compact" key={r.id}><strong>{r.content_reference}</strong><span>{r.status} · {date(r.created_at)}</span></div>):<Empty>No takedown requests.</Empty>}</section></div></>;
}

async function Billing({creatorId,plan}:{creatorId:string;plan:Plan}){
  const data=await withAuthorizedCreator(creatorId,async client=>({current:(await client.query<{name:string;code:string;billing_status:string;interval:string;current_period_ends_at:Date|null;grace_ends_at:Date|null}>("SELECT p.name,p.code,cp.billing_status::text,cp.interval,cp.current_period_ends_at,cp.grace_ends_at FROM creator_plans cp JOIN plans p ON p.id=cp.plan_id WHERE cp.creator_id=$1 AND cp.billing_status<>'cancelled' LIMIT 1",[creatorId])).rows[0],features:(await client.query<{feature_key:string;enabled:boolean;limit_value:string|null}>("SELECT pf.feature_key,pf.enabled,pf.limit_value::text FROM plan_features pf JOIN plans p ON p.id=pf.plan_id WHERE p.code=$2 ORDER BY pf.feature_key",[creatorId,plan])).rows}));
  return <><div id="plan-billing"><Heading title="Plan / Billing" description="SaaS billing and creator-to-fan merchant processing are intentionally separate."/></div><section className="office-stats"><article><span>Plan</span><strong>{data.current?.name??plan}</strong></article><article><span>Status</span><strong>{data.current?.billing_status??"trialing"}</strong></article><article><span>Interval</span><strong>{data.current?.interval??"monthly"}</strong></article><article><span>Period ends</span><strong className="text-value">{date(data.current?.current_period_ends_at)}</strong></article></section><section className="office-panel"><h2>Entitlements</h2>{data.features.map(f=><div className="office-row compact" key={f.feature_key}><strong>{f.feature_key}</strong><span>{f.enabled?"Enabled":"Not included"}{f.limit_value?` · limit ${num(f.limit_value)}`:""}</span></div>)}</section></>;
}

async function Settings({creatorId}:{creatorId:string}){
  const data=await withAuthorizedCreator(creatorId,async client=>(await client.query<{slug:string;status:string;age_gate_enabled:boolean;currency:string}>("SELECT c.slug,c.status::text,s.age_gate_enabled,s.currency FROM creators c JOIN creator_settings s ON s.creator_id=c.id WHERE c.id=$1",[creatorId])).rows[0]!);
  return <><Heading title="Settings" description="Workspace-wide creator configuration."/><section className="office-panel"><div className="office-row compact"><strong>Workspace slug</strong><span>{data.slug}</span></div><div className="office-row compact"><strong>Status</strong><span>{data.status}</span></div><div className="office-row compact"><strong>Age gate</strong><span>{data.age_gate_enabled?"Enabled":"Disabled"}</span></div><div className="office-row compact"><strong>Currency</strong><span>{data.currency}</span></div><p>Use Branding for public appearance, Domain for hostnames, Payment settings for merchant processors, Compliance for verification records, and Plan / Billing for SaaS entitlements.</p></section></>;
}

export async function CreatorConsole({creatorId,section="overview"}:{creatorId:string;section?:string}){
  if(!creatorSections.includes(section as CreatorSection)) notFound();
  const current=section as CreatorSection;
  const base=await withAuthorizedCreator(creatorId,async(client,_user,role)=>{
    const creator=(await client.query<{name:string;status:string}>("SELECT name,status::text FROM creators WHERE id=$1 AND deleted_at IS NULL",[creatorId])).rows[0];
    if(!creator) notFound();
    const entitlements=await loadCreatorEntitlements(client,creatorId);
    return {creator,role,entitlements};
  });
  const plan=base.entitlements.plan;
  let body:React.ReactNode;
  switch(current){
    case "overview": body=<Overview creatorId={creatorId}/>; break;
    case "content": body=<Content creatorId={creatorId} plan={plan}/>; break;
    case "subscribers": body=<Subscribers creatorId={creatorId}/>; break;
    case "fans": body=<Fans creatorId={creatorId} plan={plan}/>; break;
    case "memberships": body=<Memberships creatorId={creatorId} plan={plan}/>; break;
    case "ppv": body=<Products creatorId={creatorId} plan={plan} ppvOnly/>; break;
    case "products": body=<Products creatorId={creatorId} plan={plan}/>; break;
    case "revenue": body=<Revenue creatorId={creatorId}/>; break;
    case "analytics": body=<Analytics creatorId={creatorId} plan={plan}/>; break;
    case "marketing": body=<Marketing creatorId={creatorId} plan={plan}/>; break;
    case "discounts": body=<Discounts creatorId={creatorId} plan={plan}/>; break;
    case "referrals": body=<Referrals creatorId={creatorId} plan={plan}/>; break;
    case "messages": body=<Messages creatorId={creatorId}/>; break;
    case "livestreams": body=<Livestreams creatorId={creatorId} plan={plan}/>; break;
    case "branding": body=<Branding creatorId={creatorId}/>; break;
    case "domain": body=<Domains creatorId={creatorId}/>; break;
    case "payments": body=<Payments creatorId={creatorId}/>; break;
    case "compliance": body=<Compliance creatorId={creatorId}/>; break;
    case "billing": body=<Billing creatorId={creatorId} plan={plan}/>; break;
    case "settings": body=<Settings creatorId={creatorId}/>; break;
  }
  return <CreatorShell creatorId={creatorId} creatorName={base.creator.name} plan={plan.toUpperCase()} section={current} admin={base.role==="platform_admin"}>{base.creator.status!=="active"&&<p className="office-notice">Workspace status: {base.creator.status}. Configuration is available, but public runtime access remains closed until the workspace is active.</p>}{body}</CreatorShell>;
}
