import { OfficeShell } from "@/app/components/office-shell";
import { ActionForm } from "@/app/components/action-form";
import { startCreatorOnboarding, creatorOnboardingStep } from "@/src/server/admin/onboarding";
import { withPlatformAdmin } from "@/src/server/backoffice/access";

const steps=["Basic information","Choose plan","Choose theme","Branding","Domain","Payment processor","Subscription pricing","Initial content","Compliance configuration","Launch"];

export default async function OnboardingPage({searchParams}:{searchParams:Promise<{creatorId?:string;step?:string}>}){
  const search=await searchParams; const step=Math.max(1,Math.min(10,Number(search.step)||1)); const creatorId=search.creatorId;
  const creator=creatorId?await withPlatformAdmin(async client=>(await client.query<{id:string;name:string;slug:string;status:string}>("SELECT id,name,slug,status::text FROM creators WHERE id=$1 AND deleted_at IS NULL",[creatorId])).rows[0]??null):null;
  if(step>1&&!creator) return <OfficeShell admin title="Creator onboarding" description="The selected onboarding workspace could not be found."><a className="office-button" href="/admin/onboarding">Start a new creator</a></OfficeShell>;
  return <OfficeShell admin title="Creator onboarding" description="Launch a white-label creator tenant without changing source code.">
    <div className="onboarding-progress">{steps.map((label,index)=><span key={label} className={index+1===step?"active":index+1<step?"done":""}>{index+1}<small>{label}</small></span>)}</div>
    {creator&&<p className="office-notice">Configuring <strong>{creator.name}</strong> · {creator.slug} · {creator.status}</p>}
    {step===1&&<section className="office-panel"><h2>1. Basic information</h2><ActionForm action={startCreatorOnboarding} label="Create creator & continue"><label>Creator / brand name<input name="name" required maxLength={120}/></label><label>Platform slug<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" placeholder="creator-name"/></label><label>Owner email<input name="ownerEmail" type="email" required/></label><label>Creator vertical<select name="vertical" defaultValue="creator"><option value="creator">General creator</option><option value="adult">Adult creator</option><option value="fitness">Fitness</option><option value="influencer">Influencer</option><option value="musician">Musician</option><option value="coach">Coach</option><option value="model">Model</option><option value="podcaster">Podcaster</option><option value="other">Other</option></select></label></ActionForm></section>}
    {creator&&step===2&&<Step creatorId={creator.id} step="2" title="2. Choose plan"><label>Plan<select name="plan" defaultValue="pro"><option value="starter">Starter — $149/month</option><option value="pro">Pro — $299/month</option><option value="elite">Elite — starting at $599/month</option></select></label></Step>}
    {creator&&step===3&&<Step creatorId={creator.id} step="3" title="3. Choose theme"><label>Theme<select name="preset" defaultValue="dark"><option value="luxury">Luxury</option><option value="dark">Dark</option><option value="minimal">Minimal</option><option value="glam">Pink / Glam</option><option value="lifestyle">Lifestyle</option></select></label></Step>}
    {creator&&step===4&&<Step creatorId={creator.id} step="4" title="4. Branding"><label>Bio<textarea name="bio" rows={6}/></label><label>Primary color<input name="primaryColor" type="color" defaultValue="#ff355d"/></label><label>Secondary color<input name="secondaryColor" type="color" defaultValue="#2a2732"/></label><label>Accent color<input name="accentColor" type="color" defaultValue="#ff7090"/></label></Step>}
    {creator&&step===5&&<Step creatorId={creator.id} step="5" title="5. Domain"><label>Custom hostname<input name="hostname" placeholder="creatorname.com"/></label><p>Leave blank to launch on the platform subdomain first. Custom-domain DNS verification and SSL activation are tracked separately.</p></Step>}
    {creator&&step===6&&<Step creatorId={creator.id} step="6" title="6. Payment processor"><label>Processor<select name="provider" defaultValue="later"><option value="later">Configure later</option><option value="ccbill">CCBill</option><option value="segpay">Segpay</option><option value="stripe">Stripe — eligible non-adult verticals only</option></select></label><label>Merchant / account reference<input name="merchantReference"/></label><p>This stores only the merchant reference. API credentials belong in server-side secrets, never creator-visible settings.</p></Step>}
    {creator&&step===7&&<Step creatorId={creator.id} step="7" title="7. Subscription pricing"><label>Membership name<input name="tierName" defaultValue="Premium" required/></label><label>Membership slug<input name="tierSlug" defaultValue="premium" pattern="[a-z0-9]+(-[a-z0-9]+)*" required/></label><label>Monthly price<input name="price" type="number" min="0" step="0.01" defaultValue="19.99" required/></label></Step>}
    {creator&&step===8&&<Step creatorId={creator.id} step="8" title="8. Initial content"><label>First post title<input name="title"/></label><label>Post body<textarea name="body" rows={6}/></label><label>Status<select name="publish" defaultValue="draft"><option value="draft">Save draft</option><option value="published">Publish when site launches</option></select></label></Step>}
    {creator&&step===9&&<Step creatorId={creator.id} step="9" title="9. Compliance configuration"><label>Age gate<select name="ageGate" defaultValue="on"><option value="on">Enabled</option><option value="off">Disabled for non-age-restricted vertical</option></select></label><label>Jurisdiction rules<select name="jurisdictionMode" defaultValue="legal_review"><option value="legal_review">Requires legal review</option><option value="configured">Configured by approved policy</option></select></label><label>Creator identity verification<select name="identityStatus" defaultValue="pending"><option value="pending">Pending</option><option value="review_required">Review required</option><option value="verified">Verified by approved process</option></select></label><p>Mark identity verified only when the platform has actual verification evidence. The application does not invent jurisdiction-specific legal rules.</p></Step>}
    {creator&&step===10&&<Step creatorId={creator.id} step="10" title="10. Launch" label="Finish onboarding"><label>Launch decision<select name="launch" defaultValue="keep_draft"><option value="keep_draft">Keep draft</option><option value="launch">Run launch checks and activate</option></select></label><p>Activation requires a plan, theme, membership price, owner access, and verified creator identity. Missing requirements fail closed.</p></Step>}
  </OfficeShell>;
}

function Step({creatorId,step,title,label="Save & continue",children}:{creatorId:string;step:string;title:string;label?:string;children:React.ReactNode}){
  return <section className="office-panel"><h2>{title}</h2><ActionForm action={creatorOnboardingStep} label={label}><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="step" value={step}/>{children}</ActionForm></section>;
}
