"use server";
import { createHash, randomBytes } from "node:crypto";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { withPlatformAdmin, audit } from "@/src/server/backoffice/access";
import type { FormState } from "@/app/components/action-form";

const uuid=z.string().uuid();
const email=z.string().trim().toLowerCase().email().max(320);
const hostname=z.string().trim().toLowerCase().min(3).max(253);
const money=z.coerce.number().min(0).max(100000);

function errorState(error:unknown):FormState{
  const code=(error as {code?:string}).code;
  if(code==="23505") return {ok:false,message:"That slug, domain, tier, or provider reference is already in use."};
  const message=error instanceof Error?error.message:"";
  if(message.startsWith("ONBOARD:")) return {ok:false,message:message.slice(8)};
  console.error("Onboarding failed",{code,message});
  return {ok:false,message:"This onboarding step could not be saved."};
}

export async function startCreatorOnboarding(_state:FormState,form:FormData):Promise<FormState>{
  const parsed=z.object({name:z.string().trim().min(1).max(120),slug:z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(63),ownerEmail:email,vertical:z.enum(["creator","adult","fitness","influencer","musician","coach","model","podcaster","other"])}).safeParse(Object.fromEntries(form));
  if(!parsed.success) return {ok:false,message:"Enter a valid creator name, slug, owner email and vertical."};
  let id="";
  try{
    id=await withPlatformAdmin(async(client,actor)=>{
      const creator=(await client.query<{id:string}>("INSERT INTO creators(name,slug,vertical,status) VALUES($1,$2,$3,'draft') RETURNING id",[parsed.data.name,parsed.data.slug,parsed.data.vertical])).rows[0]!;
      await client.query("INSERT INTO creator_settings(creator_id) VALUES($1)",[creator.id]);
      await client.query("INSERT INTO onboarding_progress(creator_id,current_step,completed_steps) VALUES($1,2,ARRAY[1])",[creator.id]);
      const owner=(await client.query<{id:string}>("SELECT id FROM platform_users WHERE lower(email)=$1 AND disabled_at IS NULL",[parsed.data.ownerEmail])).rows[0];
      if(owner) await client.query("INSERT INTO creator_users(creator_id,user_id,role) VALUES($1,$2,'owner') ON CONFLICT DO NOTHING",[creator.id,owner.id]);
      else {
        const token=randomBytes(32).toString("base64url");
        const tokenHash=createHash("sha256").update(token).digest("hex");
        await client.query("INSERT INTO creator_invites(creator_id,email,role,token_hash,expires_at,created_by) VALUES($1,$2,'owner',$3,now()+interval '7 days',$4)",[creator.id,parsed.data.ownerEmail,tokenHash,actor.id]);
        await client.query("INSERT INTO notifications(creator_id,channel,template_key,subject,body,status,metadata) VALUES($1,'email','creator_owner_invite','Your creator workspace invitation','Complete your account setup using the secure invitation link generated by the platform.','queued',$2::jsonb)",[creator.id,JSON.stringify({recipient:parsed.data.ownerEmail,inviteToken:token})]);
      }
      await audit(client,actor.id,"onboarding.started","creator",creator.id,creator.id,{ownerEmail:parsed.data.ownerEmail,vertical:parsed.data.vertical});
      return creator.id;
    });
  }catch(error){return errorState(error);}
  redirect(`/admin/onboarding?creatorId=${id}&step=2`);
}

const stepSchema=z.discriminatedUnion("step",[
  z.object({creatorId:uuid,step:z.literal("2"),plan:z.enum(["starter","pro","elite"])}),
  z.object({creatorId:uuid,step:z.literal("3"),preset:z.enum(["luxury","dark","minimal","glam","lifestyle"])}),
  z.object({creatorId:uuid,step:z.literal("4"),bio:z.string().trim().max(5000),primaryColor:z.string().regex(/^#[0-9a-fA-F]{6}$/),secondaryColor:z.string().regex(/^#[0-9a-fA-F]{6}$/),accentColor:z.string().regex(/^#[0-9a-fA-F]{6}$/)}),
  z.object({creatorId:uuid,step:z.literal("5"),hostname:hostname.or(z.literal(""))}),
  z.object({creatorId:uuid,step:z.literal("6"),provider:z.enum(["ccbill","segpay","stripe","later"]),merchantReference:z.string().trim().max(255)}),
  z.object({creatorId:uuid,step:z.literal("7"),tierName:z.string().trim().min(1).max(120),tierSlug:z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(63),price:money}),
  z.object({creatorId:uuid,step:z.literal("8"),title:z.string().trim().max(200),body:z.string().trim().max(10000),publish:z.enum(["draft","published"])}),
  z.object({creatorId:uuid,step:z.literal("9"),ageGate:z.enum(["on","off"]),jurisdictionMode:z.enum(["legal_review","configured"]),identityStatus:z.enum(["pending","verified","review_required"])}),
  z.object({creatorId:uuid,step:z.literal("10"),launch:z.enum(["launch","keep_draft"])})
]);

export async function creatorOnboardingStep(_state:FormState,form:FormData):Promise<FormState>{
  const parsed=stepSchema.safeParse(Object.fromEntries(form));
  if(!parsed.success) return {ok:false,message:"Check the fields for this onboarding step."};
  const data=parsed.data;
  let next=Number(data.step)+1;
  try{
    await withPlatformAdmin(async(client,actor)=>{
      const creator=(await client.query<{id:string;status:string}>("SELECT id,status::text FROM creators WHERE id=$1 AND deleted_at IS NULL FOR UPDATE",[data.creatorId])).rows[0];
      if(!creator) throw new Error("ONBOARD:Creator workspace no longer exists.");
      if(data.step==="2"){
        const plan=(await client.query<{id:string}>("SELECT id FROM plans WHERE code=$1 AND active",[data.plan])).rows[0];
        if(!plan) throw new Error("ONBOARD:Selected plan is unavailable.");
        await client.query("UPDATE creator_plans SET billing_status='cancelled',updated_at=now() WHERE creator_id=$1 AND billing_status<>'cancelled'",[data.creatorId]);
        await client.query("INSERT INTO creator_plans(creator_id,plan_id,billing_status,interval) VALUES($1,$2,'trialing','monthly')",[data.creatorId,plan.id]);
      }else if(data.step==="3"){
        const theme=(await client.query<{id:string}>("INSERT INTO creator_themes(creator_id,preset) VALUES($1,$2) RETURNING id",[data.creatorId,data.preset])).rows[0]!;
        await client.query("UPDATE creator_settings SET theme_id=$2,updated_at=now() WHERE creator_id=$1",[data.creatorId,theme.id]);
      }else if(data.step==="4"){
        await client.query("UPDATE creator_settings SET bio=$2,settings=settings||$3::jsonb,updated_at=now() WHERE creator_id=$1",[data.creatorId,data.bio,JSON.stringify({primaryColor:data.primaryColor,secondaryColor:data.secondaryColor,accentColor:data.accentColor})]);
      }else if(data.step==="5"){
        if(data.hostname) await client.query("INSERT INTO creator_domains(creator_id,hostname,status,is_primary) VALUES($1,$2,'pending',true)",[data.creatorId,data.hostname]);
      }else if(data.step==="6"){
        if(data.provider!=="later"){
          if(!data.merchantReference) throw new Error("ONBOARD:Enter the approved merchant/account reference or choose configure later.");
          await client.query("INSERT INTO payment_provider_accounts(creator_id,provider,merchant_reference,status) VALUES($1,$2,$3,'pending')",[data.creatorId,data.provider,data.merchantReference]);
        }
      }else if(data.step==="7"){
        const cents=Math.round(data.price*100);
        await client.query("UPDATE creator_settings SET subscription_price_minor=$2,updated_at=now() WHERE creator_id=$1",[data.creatorId,cents]);
        await client.query("INSERT INTO membership_tiers(creator_id,name,slug,monthly_price_minor,position) VALUES($1,$2,$3,$4,0)",[data.creatorId,data.tierName,data.tierSlug,cents]);
      }else if(data.step==="8"){
        if(data.title||data.body) await client.query("INSERT INTO content_posts(creator_id,title,body,post_type,status,access_type,published_at,created_by) VALUES($1,$2,$3,'text',$4,'public',CASE WHEN $4='published' THEN now() ELSE NULL END,$5)",[data.creatorId,data.title||null,data.body,data.publish,actor.id]);
      }else if(data.step==="9"){
        await client.query("UPDATE creator_settings SET age_gate_enabled=$2,settings=settings||$3::jsonb,updated_at=now() WHERE creator_id=$1",[data.creatorId,data.ageGate==="on",JSON.stringify({jurisdictionVerificationMode:data.jurisdictionMode})]);
        await client.query("INSERT INTO compliance_records(creator_id,subject_type,subject_id,requirement_key,status,reviewed_by) VALUES($1,'creator',$1::text,'creator_identity',$2,$3)",[data.creatorId,data.identityStatus,actor.id]);
      }else if(data.step==="10"){
        next=10;
        if(data.launch==="launch"){
          const checks=(await client.query<{plan:boolean;theme:boolean;tier:boolean;identity_ok:boolean;owner_access:boolean}>(`SELECT
            EXISTS(SELECT 1 FROM creator_plans WHERE creator_id=$1 AND billing_status IN ('trialing','active','grace')) plan,
            EXISTS(SELECT 1 FROM creator_settings WHERE creator_id=$1 AND theme_id IS NOT NULL) theme,
            EXISTS(SELECT 1 FROM membership_tiers WHERE creator_id=$1 AND active) tier,
            EXISTS(SELECT 1 FROM compliance_records WHERE creator_id=$1 AND requirement_key='creator_identity' AND status='verified') identity_ok,
            (EXISTS(SELECT 1 FROM creator_users WHERE creator_id=$1 AND role='owner') OR EXISTS(SELECT 1 FROM creator_invites WHERE creator_id=$1 AND role='owner' AND accepted_at IS NULL AND expires_at>now())) owner_access`,[data.creatorId])).rows[0]!;
          const missing=[!checks.plan&&"plan",!checks.theme&&"theme",!checks.tier&&"membership pricing",!checks.identity_ok&&"verified creator identity",!checks.owner_access&&"owner access"].filter(Boolean);
          if(missing.length) throw new Error(`ONBOARD:Launch is blocked until these required checks are complete: ${missing.join(", ")}.`);
          await client.query("UPDATE creators SET status='active',launched_at=coalesce(launched_at,now()),updated_at=now() WHERE id=$1",[data.creatorId]);
          await client.query("UPDATE onboarding_progress SET launched_at=now(),updated_at=now() WHERE creator_id=$1",[data.creatorId]);
        }
      }
      const stepNo=Number(data.step);
      await client.query("INSERT INTO onboarding_progress(creator_id,current_step,completed_steps,updated_at) VALUES($1,$2,ARRAY[$3],now()) ON CONFLICT(creator_id) DO UPDATE SET current_step=$2,completed_steps=(SELECT ARRAY(SELECT DISTINCT x FROM unnest(onboarding_progress.completed_steps||ARRAY[$3]) x ORDER BY x)),updated_at=now()",[data.creatorId,Math.min(10,next),stepNo]);
      await audit(client,actor.id,`onboarding.step.${data.step}`,"creator",data.creatorId,data.creatorId);
    });
  }catch(error){return errorState(error);}
  revalidatePath("/admin","layout");
  if(data.step==="10") redirect(`/admin/clients/${data.creatorId}`);
  redirect(`/admin/onboarding?creatorId=${data.creatorId}&step=${next}`);
}
