import { notFound } from "next/navigation";
import { z } from "zod";
import { CreatorShell } from "@/app/components/creator-shell";
import { ActionForm } from "@/app/components/action-form";
import { creatorAction } from "@/src/server/creator/actions";
import { withAuthorizedCreator } from "@/src/modules/auth/authorization";
import { loadCreatorEntitlements } from "@/src/modules/entitlements/server";
import { planIncludesFeature } from "@/src/modules/entitlements/policy";

const when=(v:Date|null)=>v?v.toLocaleString():"—";
export default async function ContentPage({params}:{params:Promise<{creatorId:string}>}){const {creatorId}=await params;if(!z.string().uuid().safeParse(creatorId).success)notFound();const data=await withAuthorizedCreator(creatorId,async(client,_a,role)=>{const creator=(await client.query<{name:string}>("SELECT name FROM creators WHERE id=$1",[creatorId])).rows[0];if(!creator)return null;const ent=await loadCreatorEntitlements(client,creatorId);const posts=(await client.query<{id:string;title:string|null;post_type:string;status:string;access_type:string;published_at:Date|null;scheduled_for:Date|null;archived_at:Date|null;media_count:string;held:boolean}>(`SELECT p.id,p.title,p.post_type,p.status,p.access_type,p.published_at,p.scheduled_for,p.archived_at,(SELECT count(*) FROM post_media pm WHERE pm.creator_id=p.creator_id AND pm.post_id=p.id)::text media_count,EXISTS(SELECT 1 FROM content_holds h WHERE h.creator_id=p.creator_id AND h.post_id=p.id AND h.status='active') held FROM content_posts p WHERE p.creator_id=$1 ORDER BY p.updated_at DESC LIMIT 250`,[creatorId])).rows;const tiers=(await client.query<{id:string;name:string}>("SELECT id,name FROM membership_tiers WHERE creator_id=$1 AND active ORDER BY position,name",[creatorId])).rows;return{creator,role,plan:ent.plan,posts,tiers};});if(!data)notFound();return <CreatorShell creatorId={creatorId} creatorName={data.creator.name} plan={data.plan.toUpperCase()} section="content" admin={data.role==="platform_admin"}><div className="office-heading"><h1>Content</h1><p>Create, schedule, publish, archive and attach protected media without changing source code.</p><a className="office-button" href={`/dashboard/${creatorId}/content/upload`}>Upload media</a></div>
  <section className="office-panel"><h2>Create post</h2><ActionForm action={creatorAction} label="Create post"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="post"/><label>Title<input name="title" maxLength={200}/></label><label>Body<textarea name="body" rows={5}/></label><label>Type<select name="postType" defaultValue="text"><option value="text">Text</option><option value="image">Image</option><option value="video">Video</option><option value="gallery">Gallery</option><option value="mixed">Mixed media</option></select></label><label>Access<select name="accessType" defaultValue="public"><option value="public">Public</option><option value="subscriber">Subscribers</option><option value="membership">Membership tier</option>{planIncludesFeature(data.plan,"ppv")&&<option value="ppv">PPV</option>}</select></label><label>Membership tier<select name="membershipTierId" defaultValue=""><option value="">Not tier-specific</option>{data.tiers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{planIncludesFeature(data.plan,"ppv")&&<label>PPV price<input name="price" type="number" min="0" step="0.01"/></label>}<label>Initial status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="published">Publish now</option></select></label></ActionForm></section>
  <section className="office-list">{data.posts.length?data.posts.map(post=><article className="office-panel office-row" key={post.id}><div><a href={`/dashboard/${creatorId}/content/${post.id}`}><strong>{post.title||"Untitled post"}</strong></a><p>{post.post_type} · {post.access_type} · {post.status} · {post.media_count} media{post.held?" · PLATFORM HOLD":""}</p></div><span>{post.status==="scheduled"?`Scheduled ${when(post.scheduled_for)}`:post.status==="published"?`Published ${when(post.published_at)}`:post.status==="archived"?`Archived ${when(post.archived_at)}`:"Draft"}</span></article>):<p className="office-empty">No content yet.</p>}</section></CreatorShell>;}
