import { notFound } from "next/navigation";
import { z } from "zod";
import { CreatorShell } from "@/app/components/creator-shell";
import { ActionForm } from "@/app/components/action-form";
import { withAuthorizedCreator } from "@/src/modules/auth/authorization";
import { loadCreatorEntitlements } from "@/src/modules/entitlements/server";
import { planIncludesFeature } from "@/src/modules/entitlements/policy";
import { crmAction } from "@/src/server/crm/actions";

const money=(minor:string|number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(minor)/100);const when=(v:Date|null)=>v?v.toLocaleDateString():"—";
export default async function FansPage({params}:{params:Promise<{creatorId:string}>}){const {creatorId}=await params;if(!z.string().uuid().safeParse(creatorId).success)notFound();const data=await withAuthorizedCreator(creatorId,async(client,_actor,role)=>{const creator=(await client.query<{name:string}>("SELECT name FROM creators WHERE id=$1",[creatorId])).rows[0];if(!creator)return null;const ent=await loadCreatorEntitlements(client,creatorId);const fans=(await client.query<{id:string;email:string;display_name:string|null;created_at:Date;last_login_at:Date|null;disabled_at:Date|null;lifetime:string;sub_status:string|null;ppv:string}>(`SELECT f.id,f.email,fp.display_name,f.created_at,f.last_login_at,f.disabled_at,coalesce((SELECT sum(t.gross_minor) FROM transactions t WHERE t.creator_id=f.creator_id AND t.fan_id=f.id AND t.status='settled'),0)::text lifetime,(SELECT status FROM creator_subscriptions s WHERE s.creator_id=f.creator_id AND s.fan_id=f.id ORDER BY created_at DESC LIMIT 1) sub_status,coalesce((SELECT count(*) FROM purchases p JOIN products pr ON pr.creator_id=p.creator_id AND pr.id=p.product_id WHERE p.creator_id=f.creator_id AND p.fan_id=f.id AND p.status='paid' AND pr.product_type='ppv'),0)::text ppv FROM fans f LEFT JOIN fan_profiles fp ON fp.creator_id=f.creator_id AND fp.fan_id=f.id WHERE f.creator_id=$1 ORDER BY f.created_at DESC LIMIT 300`,[creatorId])).rows;const segments=(await client.query<{id:string;name:string;rules:Record<string,unknown>;is_system:boolean}>("SELECT id,name,rules,is_system FROM segments WHERE creator_id=$1 ORDER BY is_system DESC,name",[creatorId])).rows;const tags=(await client.query<{id:string;name:string}>("SELECT id,name FROM crm_tags WHERE creator_id=$1 ORDER BY name",[creatorId])).rows;return{creator,role,plan:ent.plan,fans,segments,tags};});if(!data)notFound();const enabled=planIncludesFeature(data.plan,"crm");return <CreatorShell creatorId={creatorId} creatorName={data.creator.name} plan={data.plan.toUpperCase()} section="fans" admin={data.role==="platform_admin"}><div className="office-heading"><h1>Customers / Fans</h1><p>Profiles, LTV, membership state, PPV behavior, tags, notes, acquisition and saved segments.</p></div>
  {!enabled?<section className="office-panel feature-lock"><h2>CRM requires Pro or Elite</h2><p>The tenant data remains isolated and available to the platform, but creator CRM controls are entitlement-gated.</p></section>:<><section className="office-panel"><h2>Create saved segment</h2><ActionForm action={crmAction} label="Save segment"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="operation" value="segment-create"/><label>Name<input name="name" required/></label><label>Subscription status<select name="subscriptionStatus" defaultValue=""><option value="">Any</option><option value="active">Active</option><option value="trialing">Trial</option><option value="past_due">Past due</option><option value="cancelled">Cancelled</option><option value="expired">Expired</option></select></label><label>Minimum lifetime spend ($)<input name="minSpend" type="number" min="0" step="1"/></label><label>Inactive at least days<input name="inactiveDays" type="number" min="0" step="1"/></label><label>At least PPV purchases<input name="ppvPurchases" type="number" min="0" step="1"/></label><label>Has tag<select name="tagId" defaultValue=""><option value="">Any</option>{data.tags.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label></ActionForm></section><section className="office-panel"><h2>Segments</h2>{data.segments.map(s=><div className="office-row compact" key={s.id}><div><strong>{s.name}</strong><small>{s.is_system?"System":"Saved"}</small></div><span>{Object.entries(s.rules).map(([k,v])=>`${k}: ${JSON.stringify(v)}`).join(" · ")||"All fans"}</span></div>)}</section></>}
  <section className="office-list">{data.fans.length?data.fans.map(f=><article className="office-panel office-row" key={f.id}><div><a href={`/dashboard/${creatorId}/fans/${f.id}`}><strong>{f.display_name||f.email}</strong></a><p>{f.email} · joined {when(f.created_at)} · last login {when(f.last_login_at)}</p></div><div><strong>{money(f.lifetime)}</strong><small>{f.sub_status||"no membership"} · {f.ppv} PPV · {f.disabled_at?"suspended":"active"}</small></div></article>):<p className="office-empty">No fan accounts yet.</p>}</section></CreatorShell>;}
