import { notFound } from "next/navigation";
import { z } from "zod";
import { CreatorShell } from "@/app/components/creator-shell";
import { ActionForm } from "@/app/components/action-form";
import { LiveBroadcaster } from "@/app/components/live-broadcaster";
import { withAuthorizedCreator } from "@/src/modules/auth/authorization";
import { loadCreatorEntitlements } from "@/src/modules/entitlements/server";
import { planIncludesFeature } from "@/src/modules/entitlements/policy";
import { liveStreamAction } from "@/src/server/live/actions";
import { liveModerationAction } from "@/src/server/live/moderation";
import { liveEngagementAction } from "@/src/server/live/engagement-actions";

const money=(minor:number,currency:string)=>new Intl.NumberFormat("en-US",{style:"currency",currency}).format(minor/100);

export default async function LiveStudioPage({params}:{params:Promise<{creatorId:string;streamId:string}>}){
  const {creatorId,streamId}=await params;
  if(!z.string().uuid().safeParse(creatorId).success||!z.string().uuid().safeParse(streamId).success)notFound();
  const data=await withAuthorizedCreator(creatorId,async(client,_user,role)=>{
    const creator=(await client.query<{name:string}>("SELECT name FROM creators WHERE id=$1 AND deleted_at IS NULL LIMIT 1",[creatorId])).rows[0];
    const stream=(await client.query<{id:string;title:string;description:string;status:string;access_type:string;provider:string;provider_stream_id:string|null;chat_enabled:boolean;scheduled_for:Date|null;started_at:Date|null;ended_at:Date|null;currency:string;ppv_price_minor:number|null}>("SELECT id,title,description,status,access_type,provider,provider_stream_id,chat_enabled,scheduled_for,started_at,ended_at,currency,ppv_price_minor FROM live_streams WHERE creator_id=$1 AND id=$2",[creatorId,streamId])).rows[0];
    if(!creator||!stream)return null;
    const ent=await loadCreatorEntitlements(client,creatorId);
    const sample=(await client.query<{concurrent_viewers:number;unique_viewers:string;gross_revenue_minor:string}>("SELECT concurrent_viewers,unique_viewers::text,gross_revenue_minor::text FROM live_analytics_samples WHERE creator_id=$1 AND stream_id=$2 ORDER BY sampled_at DESC LIMIT 1",[creatorId,streamId])).rows[0];
    const revenue=(await client.query<{gross:string;tips:string}>(`SELECT coalesce(sum(t.gross_minor) FILTER (WHERE t.status='settled'),0)::text AS gross,
      coalesce((SELECT sum(amount_minor) FROM tips WHERE creator_id=$1 AND live_stream_id=$2),0)::text AS tips
      FROM transactions t WHERE t.creator_id=$1 AND (t.metadata->>'streamId'=$2::text OR t.id IN (SELECT transaction_id FROM tips WHERE creator_id=$1 AND live_stream_id=$2))`,[creatorId,streamId])).rows[0]!;
    const chat=(await client.query<{id:string;fan_id:string|null;email:string|null;body:string;created_at:Date}>(`SELECT m.id,m.fan_id,f.email,m.body,m.created_at FROM live_chat_messages m LEFT JOIN fans f ON f.creator_id=m.creator_id AND f.id=m.fan_id
      WHERE m.creator_id=$1 AND m.stream_id=$2 AND m.status='visible' ORDER BY m.created_at DESC LIMIT 50`,[creatorId,streamId])).rows;
    const products=(await client.query<{id:string;name:string;price_minor:number;currency:string}>("SELECT id,name,price_minor,currency FROM products WHERE creator_id=$1 AND active ORDER BY created_at DESC LIMIT 100",[creatorId])).rows;
    const polls=(await client.query<{id:string;question:string;status:string;created_at:Date}>("SELECT id,question,status,created_at FROM live_polls WHERE creator_id=$1 AND stream_id=$2 ORDER BY created_at DESC",[creatorId,streamId])).rows;
    const pollOptions=(await client.query<{id:string;poll_id:string;label:string;position:number;votes:string}>(`SELECT o.id,o.poll_id,o.label,o.position,count(v.fan_id)::text votes FROM live_poll_options o LEFT JOIN live_poll_votes v ON v.creator_id=o.creator_id AND v.poll_id=o.poll_id AND v.option_id=o.id WHERE o.creator_id=$1 AND o.poll_id IN (SELECT id FROM live_polls WHERE creator_id=$1 AND stream_id=$2) GROUP BY o.id,o.poll_id,o.label,o.position ORDER BY o.poll_id,o.position`,[creatorId,streamId])).rows;
    const offers=(await client.query<{id:string;headline:string;status:string;product_name:string;price_minor:number;currency:string}>(`SELECT o.id,o.headline,o.status,p.name product_name,p.price_minor,p.currency FROM live_offers o JOIN products p ON p.creator_id=o.creator_id AND p.id=o.product_id WHERE o.creator_id=$1 AND o.stream_id=$2 ORDER BY o.created_at DESC`,[creatorId,streamId])).rows;
    const guests=(await client.query<{id:string;guest_label:string;status:string;expires_at:Date;accepted_at:Date|null}>("SELECT id,guest_label,status,expires_at,accepted_at FROM live_guest_invites WHERE creator_id=$1 AND stream_id=$2 ORDER BY created_at DESC LIMIT 100",[creatorId,streamId])).rows;
    return{creator,stream,role,plan:ent.plan,sample,revenue,chat,products,polls,pollOptions,offers,guests};
  });
  if(!data)notFound();
  const canManage=["owner","admin","editor","platform_admin"].includes(data.role);
  const canModerate=["owner","admin","platform_admin"].includes(data.role);
  const elitePolls=planIncludesFeature(data.plan,"livePolls"),eliteOffers=planIncludesFeature(data.plan,"liveOffers"),eliteGuests=planIncludesFeature(data.plan,"liveGuests");
  return <CreatorShell creatorId={creatorId} creatorName={data.creator.name} plan={data.plan.toUpperCase()} section="livestreams">
    <div className="creator-console-heading"><div><small>LIVESTREAM STUDIO</small><h1>{data.stream.title}</h1><p>{data.stream.description||"Manage the live event, broadcast, audience and moderation."}</p></div><span className={`creator-status ${data.stream.status}`}>{data.stream.status}</span></div>
    <section className="creator-metric-grid"><article><span>Current viewers</span><strong>{data.sample?.concurrent_viewers??0}</strong></article><article><span>Unique viewers</span><strong>{data.sample?.unique_viewers??"0"}</strong></article><article><span>Live revenue</span><strong>{money(Number(data.revenue.gross||0)+Number(data.revenue.tips||0),data.stream.currency)}</strong></article><article><span>Access</span><strong className="creator-text-metric">{data.stream.access_type}</strong></article></section>
    {canManage&&<section className="creator-card"><div className="creator-card-head"><div><small>STREAM CONTROL</small><h2>Go live</h2></div></div><div className="creator-inline-actions">{["draft","scheduled"].includes(data.stream.status)&&<ActionForm action={liveStreamAction} label="Start stream"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="operation" value="start"/><p>Creates the provider room and opens broadcasting. Viewers still require server-side admission.</p></ActionForm>}{data.stream.status==="live"&&<ActionForm action={liveStreamAction} label="End stream"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="operation" value="end"/><p>Ends the provider room and revokes active admissions.</p></ActionForm>}</div></section>}
    {data.stream.status==="live"&&canManage&&<LiveBroadcaster creatorId={creatorId} streamId={streamId}/>} 
    <section className="creator-card"><div className="creator-card-head"><div><small>LIVE CHAT</small><h2>Recent messages</h2></div><span>{data.chat.length}</span></div>{data.chat.length?data.chat.map(message=><article className="creator-list-row" key={message.id}><div><strong>{message.email??"Guest"}</strong><p>{message.body}</p><small>{message.created_at.toLocaleString()}</small></div>{canModerate&&message.fan_id&&<div className="creator-inline-actions"><ActionForm action={liveModerationAction} label="Mute"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="fanId" value={message.fan_id}/><input type="hidden" name="action" value="mute"/></ActionForm><ActionForm action={liveModerationAction} label="Block"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="fanId" value={message.fan_id}/><input type="hidden" name="action" value="block"/></ActionForm><ActionForm action={liveModerationAction} label="Delete"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="messageId" value={message.id}/><input type="hidden" name="action" value="delete_message"/></ActionForm></div>}</article>):<p>No live chat messages yet.</p>}</section>
    {canManage&&<section className="creator-card"><div className="creator-card-head"><div><small>ELITE ENGAGEMENT</small><h2>Polls</h2></div></div>{!elitePolls?<p>Live polls require Elite.</p>:<><ActionForm action={liveEngagementAction} label="Create poll"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="operation" value="poll-create"/><label>Question<input name="question" required maxLength={500}/></label><label>Options<textarea name="options" rows={4} placeholder={'Option one\nOption two'} required/></label></ActionForm>{data.polls.map(p=><article className="creator-list-row" key={p.id}><div><strong>{p.question}</strong>{data.pollOptions.filter(o=>o.poll_id===p.id).map(o=><p key={o.id}>{o.label}: {o.votes} votes</p>)}</div><div className="creator-inline-actions">{p.status!=="open"&&<ActionForm action={liveEngagementAction} label="Open"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="pollId" value={p.id}/><input type="hidden" name="operation" value="poll-open"/></ActionForm>}{p.status==="open"&&<ActionForm action={liveEngagementAction} label="Close"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="pollId" value={p.id}/><input type="hidden" name="operation" value="poll-close"/></ActionForm>}</div></article>)}</>}</section>}
    {canManage&&<section className="creator-card"><div className="creator-card-head"><div><small>ELITE COMMERCE</small><h2>Pinned offers</h2></div></div>{!eliteOffers?<p>Pinned live offers require Elite.</p>:<><ActionForm action={liveEngagementAction} label="Create offer"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="operation" value="offer-create"/><label>Product<select name="productId" required>{data.products.map(p=><option key={p.id} value={p.id}>{p.name} · {money(p.price_minor,p.currency)}</option>)}</select></label><label>Headline<input name="headline" required maxLength={300}/></label></ActionForm>{data.offers.map(o=><article className="creator-list-row" key={o.id}><div><strong>{o.headline}</strong><p>{o.product_name} · {money(o.price_minor,o.currency)} · {o.status}</p></div><div className="creator-inline-actions">{o.status!=="pinned"&&o.status!=="ended"&&<ActionForm action={liveEngagementAction} label="Pin"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="offerId" value={o.id}/><input type="hidden" name="operation" value="offer-pin"/></ActionForm>}{o.status==="pinned"&&<ActionForm action={liveEngagementAction} label="End offer"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="offerId" value={o.id}/><input type="hidden" name="operation" value="offer-end"/></ActionForm>}</div></article>)}</>}</section>}
    {canManage&&<section className="creator-card"><div className="creator-card-head"><div><small>ELITE GUESTS</small><h2>Guest invitations</h2></div></div>{!eliteGuests?<p>Guest broadcasting requires Elite.</p>:<><ActionForm action={liveEngagementAction} label="Create guest invite"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="operation" value="guest-create"/><label>Guest label<input name="guestLabel" required/></label><label>Expires in minutes<input name="expiresMinutes" type="number" min="5" max="1440" defaultValue="60" required/></label></ActionForm>{data.guests.map(g=><article className="creator-list-row" key={g.id}><div><strong>{g.guest_label}</strong><p>{g.status} · expires {g.expires_at.toLocaleString()}</p></div>{g.status==="pending"&&<ActionForm action={liveEngagementAction} label="Revoke"><input type="hidden" name="creatorId" value={creatorId}/><input type="hidden" name="streamId" value={streamId}/><input type="hidden" name="guestId" value={g.id}/><input type="hidden" name="operation" value="guest-revoke"/></ActionForm>}</article>)}</>}</section>}
  </CreatorShell>;
}
